Fix Uncaught (in promise) TypeError
Using sail npm install npm packages, visit Home vue page and click on
Users and Settings, it doesn't do anything.  In devtools, this error is
shown:

Uncaught (in promise) TypeError: this.resolveComponent is not a function
at n2.setPage (@inertiajs_inertia-vue3.js?v=b33e0acc:7995:37)
at @inertiajs_inertia-vue3.js?v=b33e0acc:7965:111

In Commit 7ba8cb58071d ("Use global component for Link") when we moved
from @inertiajs/inertia-vue3 to @inertiajs/vue3, we should have taken
care of this issue.

The issue stays with @inertiajs/inertia-vue3 since it is obsolete and
should not be used.

Fix the error by using @inertiajs/vue3.